import Cocoa
import Combine

class ClipboardManager: ObservableObject {
    @Published var items: [ClipboardItem] = []
    private var timer: AnyCancellable?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private var maxItems: Int { Preferences.shared.clipboardHistoryLimit }

    /// Pasteboard types that mark content as not-for-history.
    ///
    /// Password managers (1Password, Bitwarden, KeePassXC, Keychain Access, …) tag copies
    /// with these so clipboard managers skip them. Without this check MacNotch happily
    /// captured every copied password and rendered it in a visible list on screen.
    ///
    /// See http://nspasteboard.org — the de-facto convention on macOS.
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        // Older marker still used by some password managers.
        NSPasteboard.PasteboardType("com.agilebits.onepassword")
    ]

    struct ClipboardItem: Identifiable, Equatable {
        let id = UUID()
        let content: String
        let timestamp: Date

        var preview: String {
            let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.count > 100 {
                return String(trimmed.prefix(97)) + "..."
            }
            return trimmed
        }
    }

    init() {
        startMonitoring()
        // Seed `lastChangeCount` without capturing whatever happens to be on the
        // pasteboard at launch — that content predates the user opting into history.
        lastChangeCount = NSPasteboard.general.changeCount
    }

    deinit {
        timer?.cancel()
    }

    func startMonitoring() {
        timer = Timer.publish(every: 0.5, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in
                self?.checkClipboard()
            }
    }

    /// True when the current pasteboard contents are marked private by the app that
    /// wrote them, in which case they must not be recorded.
    private func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        guard let available = pasteboard.types else { return false }
        return ClipboardManager.concealedTypes.contains(where: available.contains)
    }

    private func checkClipboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Consume the change count above so a concealed copy is skipped exactly once
        // rather than being re-evaluated on every tick.
        guard !isConcealed(pasteboard) else { return }

        if let newString = pasteboard.string(forType: .string) {
            let trimmed = newString.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return }

            // Avoid duplicates at the top of the history
            if items.first?.content == trimmed {
                return
            }

            // Remove previous occurrence if it exists to bring it to the top
            items.removeAll { $0.content == trimmed }

            let newItem = ClipboardItem(content: trimmed, timestamp: Date())
            items.insert(newItem, at: 0)

            // Limit items
            if items.count > maxItems {
                items.removeLast(items.count - maxItems)
            }
        }
    }

    func copyToClipboard(item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(item.content, forType: .string)
        // Update change count so we don't trigger our own duplicate detection
        lastChangeCount = pasteboard.changeCount

        // Move copied item to the top of the list
        items.removeAll { $0.id == item.id }
        items.insert(ClipboardItem(content: item.content, timestamp: Date()), at: 0)
    }

    func deleteItem(at indexSet: IndexSet) {
        items.remove(atOffsets: indexSet)
    }

    func clearHistory() {
        items.removeAll()
    }
}
